create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  remind_date date not null,
  remind_time time not null default '08:00',
  is_recurring boolean not null default true,
  reminder_offsets text not null default '30,7,1,0',
  contact_email text,
  contact_phone text,
  notify_email boolean not null default true,
  notify_push boolean not null default false,
  notify_sms boolean not null default false,
  last_notified date,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  reminder_id bigint references public.reminders(id) on delete cascade,
  notification_type text not null,
  status text not null default 'sent',
  message text,
  error text,
  due_date date,
  offset_days integer,
  sent_at timestamptz not null default now()
);

create index if not exists reminders_due_idx
  on public.reminders (remind_date, remind_time);

create index if not exists notification_log_sent_once_idx
  on public.notification_log (reminder_id, status, due_date, offset_days);
