create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
